import json,csv,math,statistics as st,collections,re,itertools,zipfile
from pathlib import Path
A=Path('/e/project1/m3/blank4/code/starVLA');D=Path('/e/project1/m3/blank4/code/train_downstream');O=A/'results_collected'
r=[json.loads(x) for x in (D/'docs/probe_results.jsonl').read_text().splitlines()];audit=json.loads((O/'audit_details.json').read_text())
def table(h,rs):return '\n'.join(['| '+' | '.join(h)+' |','|'+'---|'*len(h)]+['| '+' | '.join(map(str,row))+' |' for row in rs])+'\n'
def rec(n):return next(x for x in r if x['name']==n)
def val(x,f):return st.mean(x['R2_act_patch_map']) if f=='patch_mean' else x.get(f)
def pearson(x,y):
 mx,my=st.mean(x),st.mean(y);a=sum((a-mx)*(b-my) for a,b in zip(x,y));b=math.sqrt(sum((a-mx)**2 for a in x)*sum((b-my)**2 for b in y));return a/b if b else float('nan')
def ranks(x):return [1+sum(z<v for z in x)+(sum(z==v for z in x)-1)/2 for v in x]
def corr(x,y):return pearson(x,y),pearson(ranks(x),ranks(y))
cols=[('enc','R2_act_enc'),('mean','R2_act_patch_meanref'),('per-view','R2_act_enc_views'),('grid','R2_act_enc_grid'),('attn','R2_act_enc_attn'),('patch mean','patch_mean'),('patch best','R2_act_patch_best'),('patch top16','R2_act_patch_top16'),('state tok','R2_act_tok_state_tok'),('instruction','R2_act_tok_text'),('first patch','R2_act_tok_vis_first')]
lpmap={'starvla_lplus_causal':'ervla_pi_causal_actiononly_pifix_nolatent_nodrop_2gpu_s42','starvla_lplus_encdec':'ervla_pi_bidir_actiononly_pifix_nolatent_nodrop_2gpu_s42','starvla_lplus_encoder':'ervla_w_pi_encoder_actiononly'}
rcmap={'starvla_casa_causal_s4':'causal_s4','starvla_casa_encdec_s4':'v5_s4'}
corrows=[]
for label,field in cols:
 pairs=[(val(rec(n),field),audit['canonical'][run]['p']) for n,run in lpmap.items() if val(rec(n),field) is not None]
 rcps=[(val(rec(n),field),audit['rc_benchmark'][run]['pool']['p']) for n,run in rcmap.items() if val(rec(n),field) is not None]
 pr,sr=corr(*zip(*pairs)) if len(pairs)>1 else (None,None)
 rr,rs=corr(*zip(*rcps)) if len(rcps)>1 else (None,None)
 corrows.append({'readout':label,'libero_n_arms':len(pairs),'libero_pearson':pr,'libero_spearman':sr,'robocasa_n_arms':len(rcps),'robocasa_pearson':rr,'robocasa_spearman':rs})
with (O/'probe_benchmark_correlations.csv').open('w') as f:
 w=csv.DictWriter(f,fieldnames=corrows[0]);w.writeheader();w.writerows(corrows)
# downstream aggregate re-read source JSON through documented score rules.
import sys
sys.path.insert(0,str(D/'scripts'));import harvest_eval_results as h
names=['enc_dec_2b_v5_tb9216_final','enc_dec_2b_v5_final_aux_dense','enc_dec_2b_v5_aux_dense','enc_dec_2b_v5_aux_base','enc_dec_2b_v5_aux_trace_reverse','enc_dec_2b_v5_final_action_dec','enc_dec_2b_v5_final_action_head','enc_dec_2b_v5_final_action_linear','enc_dec_2b_v5_final_action_tracetime','enc_dec_2b_v5_final_action_tracetime_w001']
evals=json.loads((D/'train/outputs/dashboard_results.json').read_text());sc=[]
for n in names:
 entry=next(x for x in evals if x['name']==n);v,k=h.aggregate(h.read_summaries(Path(entry['results_json'])));sc.append([n,f'{v:.6f}',f'{k}/12',f"[raw JSON]({entry['results_json']})"])
# Patch/token coverage at explicit original 11-arm / 9-camera-cell grid.
ARM=['full_epoch','dense','snapshot1M','trace_dec','trace_head','trace_linear','trace_reverse','final_action_dec','final_action_head','final_action_linear','final_action_tracetime']
coverage=collections.defaultdict(set)
for x in r:
 n=x['name']
 if n.startswith('final_action_tracetime_w001'):continue
 arm=next((a for a in sorted(ARM,key=len,reverse=True) if n.startswith(a)),None)
 if not arm:continue
 k=(arm,x['dataset'],'wrist' if len(x.get('views') or [])>1 else 'ext')
 if 'R2_act_patch_map' in x:coverage[k].add('patch')
 if 'R2_act_tok_vis' in x:coverage[k].add('token')
missing=[k for a in ARM for ds in ['bridge','droid','libero10','libero_plus','robocasa'] for cam in ['ext','wrist'] if not(ds=='bridge' and cam=='wrist') and (k:=(a,ds,cam)) and coverage[k]!={'patch','token'}]
# one row per mapped policy/measurement, with no inherited benchmark for unrelated checkpoints.
linkage=[]
for n,run in lpmap.items():
 x=rec(n);linkage.append({'probe_name':n,'benchmark_run':run,'benchmark':'libero-plus','probe_source':str(D/'probe_logs'/x['_src']),'evaluation_source':audit['canonical'][run]['path'],'checkpoint_match':'final vs step20000 storage CRC/size match'})
for n,run in rcmap.items():
 x=rec(n);linkage.append({'probe_name':n,'benchmark_run':'ervla_robocasa365_pi_'+run,'benchmark':'robocasa365','probe_source':str(D/'probe_logs'/x['_src']),'evaluation_source':'s4_50k (17 raw tasks in results_master.csv)','checkpoint_match':'final vs step50000 storage CRC/size match'})
with (O/'probe_policy_linkage.csv').open('w') as f:w=csv.DictWriter(f,fieldnames=linkage[0]);w.writeheader();w.writerows(linkage)
p=['# Probe insights for the encoder paper — 2026-09-17','','**Use probes to choose interventions, not as a substitute for policy success. No readout is currently validated as a cheap success proxy.** The only matched LIBERO-plus policy triplet gives negative rank correlation for every measured readout. RoboCasa has only two checkpoint-matched policies with these readouts.','',
f'The regenerated record contains {len(r)} raw records. Each quoted number below is recomputed from that JSONL or its identified raw ACTPROBE source, not the markdown or HTML. The intended external/ext+wrist 11-arm × 9 dataset/camera grid has {99-len(missing)}/99 cells with both patch and token readouts. The missing 33 are LIBERO10/LIBERO-plus/RoboCasa ext+wrist cells: the completed full-table jobs actually used wrist-only cameras in those slots. Those 33 wrist-only cells exist but cannot fill ext+wrist blanks. The two flagged DROID ext+wrist cells have now landed (job1855867 COMPLETED, 25m01s); all 99 actually requested launcher cells have results. Thus the historical 82/90 statement is stale and uses a different denominator. The weight0.01 tracetime arm is separate and has pooled probes but not a complete 11-readout grid.','',
'## Matched policy probes and actual benchmark scores','',
'Final_model and named evaluation checkpoints have matching tensor-storage CRC/size inventories for the three LIBERO-plus policies (20k) and two RoboCasa seed4 policies (50k). This is a strong content check without loading weights onto a GPU; it is not a cryptographic hash of every tensor. RoboCasa seed42 probes used **40k**, while benchmark JSONs use **50k**, so that seed is excluded from checkpoint-matched correlation. [Join audit](results_collected/probe_policy_linkage.csv). All these probes use the external camera only and omit proprioception (build_qwenvl_inputs receives only images/instructions), while RoboCasa rollouts use external+wrist+state. Thus checkpoints match, inference inputs do not. n_test=960 frames from held-out episodes; do not treat frames as independent episodes.','',
table(['probe / policy','held-out n','pooled standardized R²','mean patch R²','best patch R²','top16 R²','rollout % ± SE; n','raw probe'],[(n,rec(n)['n_test'],rec(n).get('R2_act_patch_meanref'),f"{val(rec(n),'patch_mean'):.4f}",rec(n)['R2_act_patch_best'],rec(n)['R2_act_patch_top16'],f"{100*audit['canonical'][run]['p']:.3f} ± {100*audit['canonical'][run]['se']:.3f}; {audit['canonical'][run]['n']}",f"[{rec(n)['_src']}]({D/'probe_logs'/rec(n)['_src']})") for n,run in lpmap.items()]+[(n,rec(n)['n_test'],rec(n)['R2_act_patch_meanref'],f"{val(rec(n),'patch_mean'):.4f}",rec(n)['R2_act_patch_best'],rec(n)['R2_act_patch_top16'],f"{100*audit['rc_benchmark'][run]['pool']['p']:.3f} ± {100*audit['rc_benchmark'][run]['pool']['se']:.3f}; 816",f"[{rec(n)['_src']}]({D/'probe_logs'/rec(n)['_src']})") for n,run in rcmap.items()]),
'## The 11 readouts ranked against benchmark success','',
'The four observed LIBERO-plus readouts tie at Spearman −0.5 (3 arms); the other seven are unmeasured on the matched policies and cannot be ranked. Pearson is supplied only as a descriptive check. An exact two-sided permutation test on three ranks cannot reject the null here (p=1). At two RoboCasa arms, correlation ±1 is algebraic and supplies no validation. The original `enc` readout is unstandardized and must not be silently substituted for `patch_meanref`; the latter is the standardized mean column used here. Hyperparameter details may differ from pooling-sweep `mean`, so the prospective proxy study must rerun one frozen probe protocol.','',
table(['readout','LP rank / coverage','LP Pearson r','LP Spearman ρ','RC coverage / r,ρ'],[(x['readout'],'tie / 3' if x['libero_n_arms'] else 'unrankable / 0',f"{x['libero_pearson']:.3f}" if x['libero_pearson'] is not None else 'NA',f"{x['libero_spearman']:.3f}" if x['libero_spearman'] is not None else 'NA','2 / 1.000,1.000 (uninformative)' if x['robocasa_n_arms'] else '0 / NA') for x in corrows]),
'',
'Do not attach the same backbone probe to all its fine-tuned policy heads: those are different final weights and repeated copies would inflate sample size. The full_epoch/dense/trace/final_action grid has spatial/VQA evaluations, not matching LIBERO-plus or RoboCasa rollouts for every cell. [Correlation CSV](results_collected/probe_benchmark_correlations.csv). To find a usable proxy: freeze the 11 readouts and held-out episodes; probe ≥8 final policy variants including shared-z, withhold entire training seeds for validation; require positive leave-one-family-out rank correlation and prospective ordering of two new policies. Until then screen benchmark success, not R².','',
'## Where action is decodable, and what to change','',
'**Depth is not measured.** Neither the JSONL nor the patch page contains a layer sweep. `scripts/starvla_patch_probe.py` explicitly reads hidden_states[-1] (encoder output for enc-dec, last layer for causal). These files cannot establish “available earlier.” A frozen layer4/8/14/20/28 readout sweep on the matched policies is the needed measurement; only if a middle layer predicts rollout improvements should an auxiliary head be attached there.','',
'**Spatial availability is broader in the encoder, but broad availability alone does not improve control.** The matched LIBERO-plus bidirectional arm has mean-patch R²0.4208 versus causal0.2410, and best/pooled ratio0.946 versus0.722, yet its policy is 0.475 pp worse in seed42. Mechanism hypothesis: bidirectional mixing broadcasts a global state/action correlate to many token positions, while the policy head fails to extract additional control-relevant information. Experiment: compare shared-z query readout against whole-memory and equal-capacity pooled readout on the same frozen encoder; predict gains in robot-init/layout, not a uniform gain in every category.','',
'**RoboCasa’s visual signal is much stronger in the encoder despite near-equal success.** Seed4 pooled R²0.2800 versus0.0423 and mean-patch0.1321 versus0.0229 imply that a linear head can extract substantially more action-related information. Seed42 at40k repeats the direction (0.2699 versus0.0382) but is not a50k matched-success comparison. Mechanism hypothesis: useful visual encoding is present but the readout/training distribution is limiting closed-loop recovery. Experiment: shared-z or learned query readout on RoboCasa, with held-out task-level recovery tests; predict a larger gain on mobile/layout-recovery tasks than on already easy articulation tasks.','',
'**Token position is a readout opportunity, not modality attribution.**','',
table(['raw record','n_test','visual mean R²','first patch','state tokens','instruction'],[(n,rec(n)['n_test'],rec(n).get('R2_act_tok_vis'),rec(n).get('R2_act_tok_vis_first'),rec(n).get('R2_act_tok_state_tok'),rec(n).get('R2_act_tok_text')) for n in ['full_epoch_tclass_bridge','full_epoch_tclass_droid','final_action_dec_tclass_bridge','trace_reverse_tclass_bridge']]),
'',
'All records above are in docs/probe_results.jsonl with state_in_prompt=true, state_mode=tokens. Bridge n_train5592/n_test2400; DROID5600/2399, different K8 versusK15. Mechanism hypothesis: text positions offer a useful integrated summary and learned state tokens become usable when trained, but contextualized “state tokens” also contain visual information. Experiment: a small trainable query pooling text+vision, compared to vision-only under equal parameter count, with a format-preserving state ablation; predict modest gains if information routing is limiting. A state-token R² above raw-state R² does not demonstrate extra proprioceptive information.','',
'**DROID wrist addition weakens all five pooled readouts for the full-epoch model.**','',
table(['record','n_test','enc','mean','per-view','grid','attn','raw state'],[(n,rec(n)['n_test'],*[rec(n).get(f) for f in ['R2_act_enc','R2_act_enc_mean','R2_act_enc_views','R2_act_enc_grid','R2_act_enc_attn','R2_act_state']]) for n in ['full_epoch_poolsim_droid_ext','full_epoch_poolsim_droid_wrist','final_action_dec_qsim_droid_ext','final_action_dec_qsim_droid_wrist']]),
'',
'The state baseline stays0.0890 and sample counts match, unlike the old missing-camera-index bug. Full-epoch standardized mean falls0.1022→0.0757; final_action_dec falls0.1365→0.1239. Mechanism hypothesis: camera fusion or sample-limited regularization dilutes the external signal; these are ext+wr versus ext, not wrist-only measurements, so they do not prove the wrist is useless. Experiment: camera-specific normalization/query tokens and train-time single-camera dropout, then ext/wrist/ext+wr policy evaluation under camera perturbations. Keep the wrist: the published OFT benchmark reports a substantial wrist benefit, and our DROID probes do not transfer automatically to LIBERO.','',
'**The state diagnostic supports format sensitivity, with a narrower robustness benefit.** On the same three RoboCasa tasks, causal clean100/144 (69.44%)→no-state0/144; encoder105/144 (72.92%)→85/144 (59.03%). With format retained, shuffled values leave causal94/144 versus encoder87/144; random76/144 versus90/144; zero22/144 versus44/144. Mechanism hypothesis: deleting the suffix disrupts causal token routing; both policies also depend on state values, especially off-manifold zero values. Experiment: separately retain [STATE]/[ACTION] delimiters with a missing-value marker, train modest state dropout in both arms, and serialize actual prompts. Predict that much of causal’s no-state collapse disappears with format repair; require a remaining encoder advantage across ≥2 seeds before claiming proprioception robustness.','',
'**Patch brightness is not localized causal use.** DROID full_epoch mean patch0.0100→final_action_dec0.0850, best patch0.1055→0.1252, standardized mean0.1030→0.1367. Mechanism hypothesis: action co-training distributes a global summary rather than making object pixels uniquely informative. Experiment: keep readout tokens fixed and intervene on original pixels (camera shift, border occlusion versus equal-area object occlusion), then assess task success. Do not train a border-suppression loss from decodability alone. The HTML’s claim that empty-border decodability proves a visual shortcut is unsupported by a contextualized ViT/encoder map.','',
'**More decodable features can coincide with worse non-policy downstream scores.** The raw evaluation files confirm the following spatial/VQA aggregate (mean of12 score components, accuracy or exp(−DFD)); this is neither action success nor a third behavior-generation benchmark.','',table(['model','recomputed aggregate','coverage','source'],sc),
'',
'Final dense continuation decreases the full-epoch aggregate0.690442→0.671040. Tracetime weight0.01 improves over weight0.1 (0.666865 versus0.639572) but still trails the starting checkpoint. Mechanism hypothesis: aggressive auxiliary objectives redirect capacity away from general visual-language behavior. Experiment: bounded auxiliary weights0.001/0.01 with no-head continued-training control, and a matched rollout evaluation; kill if probe improves but policy success does not. A no-head continuation is necessary even when data were previously seen: optimization time and repeated exposure remain confounds.','',
'## Measurement and narrative discrepancies','',
'- Fixed collector identity collisions: historical `starVLA` patch-only records overwrote one another, and absent dataset defaulted incorrectly to Bridge. Recover from source-log basename and cache; use a full measurement fingerprint. The repaired record preserves differing historical targets rather than pretending they are replicates.','- Fixed camera grouping: single wrist-only views were incorrectly classified as external. Rows now retain camera identity, checkpoint, state mode, target dimensions/K and sample counts; prefix matching no longer folds dense_w10 into dense. The requested combined-camera grid remains incomplete even though all launcher cells completed.','- Removed the hard-coded `bench` column from build_full_table.py: it was a spatial/VQA aggregate, not LIBERO-plus/RoboCasa success. Split weight0.01 tracetime from weight0.1; prefix matching previously mixed them. Table cells remain an inventory, not permission to combine state modes, targets or checkpoints.','- The HTML labels pooled `patch_meanref` as “mean patch”; true mean patch is the mean of R2_act_patch_map and is much smaller in several arms. The page’s rollout values0.769/0.732/0.728 disagree with canonical raw values0.76425/0.725/0.72025.','- docs/STATUS.md “only enc-dec clears proprioception” holds only for the stated frozen, untrained-causal comparisons and original text-state protocol. It is not a conclusion about trained causal policies, and the quantized-token protocol gives different results.','- docs/STATUS.md final dense run and trace continuation are no longer pending; full raw evaluations exist. Dense’s early0.677429 does recompute, but calling dense the best aux policy is unsupported because that score is a VQA/spatial aggregate.','- The state-baseline, action-slice and ridge-standardization bugs described in STATUS.md remain real caveats. Historical records without explicit dimensions/state mode cannot be silently joined to corrected runs. RoboCasa n_test960 with the corrected7D end-effector/gripper target must be checked independently from12D loader order.','- starvla_patch_probe.py normalizes action targets with full-data mean/std before splitting. Per-dimension R² is affine-invariant, but any shared hyperparameter selection using normalized MSE should be rerun with train-only target statistics. This is a measurement caveat, not proof that all scores are invalid.','- No per-layer results, no matched 11-readout shared-z policy sweep, and no matching50k seed42 policy probes exist in the requested record. These block earlier-layer claims, a full correlation ranking, and seed-robust proxy validation.','- The full-table patch grids for Bridge/DROID are stored as [300,1]/[576,1], not trustworthy 2D coordinates. Geometry needs original image_grid_thw and camera token offsets; the HTML heatmap is insufficient evidence for exact patch coordinates.','',
'The probes prioritize shared-latent/readout ablations, modest auxiliary weights, camera fusion and prompt-preserving state tests. They do not independently support the encoder-paper claim.']
(A/'PROBE_INSIGHTS.md').write_text('\n'.join(p)+'\n')
print('correlations',corrows);print('missing',missing)
